version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-graphql"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k35cehhnm3o3"
s3_prefix = "sam-graphql"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
